# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Install libcore.so
      run: |
        wget https://github.com/VOICEVOX/voicevox_core/releases/download/0.13.0/voicevox_core-linux-x64-cpu-0.13.0.zip
        unzip voicevox_core-linux-x64-cpu-0.13.0.zip
        install voicevox_core-linux-x64-cpu-0.13.0/libcore.so /usr/lib/libcore.so
    - name: Install ONNX runtime
      run: |
        wget https://github.com/microsoft/onnxruntime/releases/download/v1.10.0/onnxruntime-linux-x64-1.10.0.tgz
        tar zxf onnxruntime-linux-x64-1.10.0.tgz
        install onnxruntime-linux-x64-1.10.0/lib/* /usr/lib/
    - name: Install OpenJTalk dictionary
      run: |
        wget --content-disposition https://sourceforge.net/projects/open-jtalk/files/Dictionary/open_jtalk_dic-1.11/open_jtalk_dic_utf_8-1.11.tar.gz/download
        tar zxf open_jtalk_dic_utf_8-1.11.tar.gz
    - name: Run tests
      run: sbt test
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
